sudo: required
language: minimal

env:
  global:
    - GOVERSION=1.13.8
    - GOLANGCI_LINT_VERSION=v1.24.0
    - GITHUB_RELEASE_VERSION=0.7.2

matrix:
  include:

    - os: linux
      services:
        - docker
      cache:
        directories:
        - "$HOME/.npm" # npm ci will remove node_modules; this is _its_ download cache
      script:
        - ./run-in-docker.sh make dep install test api-reference STATIC=yes

    - os: osx
      osx_image: xcode11.3
      cache:
        directories:
        - "$HOME/.npm"  # npm ci will remove node_modules; this is _its_ download cache
      before_install:
        # v8 prebuilt library
        - git clone https://github.com/jkcfg/prebuilt.git
        - make -C prebuilt install
        # go
        - (cd ~ && curl -fsSLO https://dl.google.com/go/go${GOVERSION}.darwin-amd64.tar.gz)
        - mkdir ~/go-${GOVERSION} && tar xf ~/go${GOVERSION}.darwin-amd64.tar.gz -C ~/go-${GOVERSION} --strip-components 1
        # golangci-linter
        - (cd ~ && curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s ${GOLANGCI_LINT_VERSION})
        # github-release
        - (cd ~ && curl -fsSLO https://github.com/aktau/github-release/releases/download/v${GITHUB_RELEASE_VERSION}/darwin-amd64-github-release.tar.bz2)
        - tar -xf ~/darwin-amd64-github-release.tar.bz2 -C /usr/local/bin --strip-components 3
      script:
        - export PATH=~/go-${GOVERSION}/bin:~/go/bin:$PATH
        - make dep install test

deploy:
  - skip_cleanup: true
    provider: script
    script: ./run-deploy.sh

  - skip_cleanup: true
    provider: script
    script: ./run-release.sh $TRAVIS_TAG
    on:
      tags: true
