// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package __std

type Args = byte
const (
	ArgsNONE Args = 0
	ArgsWriteArgs Args = 1
)

var EnumNamesArgs = map[Args]string{
	ArgsNONE:"NONE",
	ArgsWriteArgs:"WriteArgs",
}

