// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package __std

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// CancelArgs encodes a message cancelling a deferred response.
type CancelArgs struct {
	_tab flatbuffers.Table
}

func GetRootAsCancelArgs(buf []byte, offset flatbuffers.UOffsetT) *CancelArgs {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CancelArgs{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *CancelArgs) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CancelArgs) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CancelArgs) Serial() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CancelArgs) MutateSerial(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func CancelArgsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func CancelArgsAddSerial(builder *flatbuffers.Builder, serial uint64) {
	builder.PrependUint64Slot(0, serial, 0)
}
func CancelArgsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
