// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package __std

type DeferredRetval = byte
const (
	DeferredRetvalNONE DeferredRetval = 0
	DeferredRetvalDeferred DeferredRetval = 1
	DeferredRetvalError DeferredRetval = 2
)

var EnumNamesDeferredRetval = map[DeferredRetval]string{
	DeferredRetvalNONE:"NONE",
	DeferredRetvalDeferred:"Deferred",
	DeferredRetvalError:"Error",
}

