// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package __std

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Deferred encodes a ticket standing in for an asynchronous result.
type Deferred struct {
	_tab flatbuffers.Table
}

func GetRootAsDeferred(buf []byte, offset flatbuffers.UOffsetT) *Deferred {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Deferred{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Deferred) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Deferred) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Deferred) Serial() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Deferred) MutateSerial(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func DeferredStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func DeferredAddSerial(builder *flatbuffers.Builder, serial uint64) {
	builder.PrependUint64Slot(0, serial, 0)
}
func DeferredEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
