// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package __std

type Encoding = int8
const (
	EncodingBytes Encoding = 0
	EncodingUTF16 Encoding = 1
	EncodingJSON Encoding = 2
)

var EnumNamesEncoding = map[Encoding]string{
	EncodingBytes:"Bytes",
	EncodingUTF16:"UTF16",
	EncodingJSON:"JSON",
}

