// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package __std

/// Encoding specifies the requested form of the contents to read;
/// either just the raw bytes, or as a UTF-16 string. Distinguishing
/// String (a UTF16-encoded string) is desirable because JavaScript
/// natively supports UTF-16, so if you want to be able
/// to decode a string value conveniently, it is best to ship it as
/// UTF-16. Similarly, JSON is there as a means of sending structured
/// data, e.g., YAML, in a way that JavaScript can digest easily.
type Encoding = int8
const (
	EncodingBytes Encoding = 0
	EncodingString Encoding = 1
	EncodingJSON Encoding = 2
)

var EnumNamesEncoding = map[Encoding]string{
	EncodingBytes:"Bytes",
	EncodingString:"String",
	EncodingJSON:"JSON",
}

