// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package __std

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// EndOfStream signals that there will be no more data.
type EndOfStream struct {
	_tab flatbuffers.Table
}

func GetRootAsEndOfStream(buf []byte, offset flatbuffers.UOffsetT) *EndOfStream {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &EndOfStream{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *EndOfStream) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *EndOfStream) Table() flatbuffers.Table {
	return rcv._tab
}

func EndOfStreamStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func EndOfStreamEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
