// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package __std

type FileSystemRetval = byte
const (
	FileSystemRetvalNONE FileSystemRetval = 0
	FileSystemRetvalFileInfo FileSystemRetval = 1
	FileSystemRetvalDirectory FileSystemRetval = 2
	FileSystemRetvalError FileSystemRetval = 3
)

var EnumNamesFileSystemRetval = map[FileSystemRetval]string{
	FileSystemRetvalNONE:"NONE",
	FileSystemRetvalFileInfo:"FileInfo",
	FileSystemRetvalDirectory:"Directory",
	FileSystemRetvalError:"Error",
}

