// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package __std

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FileInfo struct {
	_tab flatbuffers.Table
}

func GetRootAsFileInfo(buf []byte, offset flatbuffers.UOffsetT) *FileInfo {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FileInfo{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *FileInfo) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FileInfo) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FileInfo) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *FileInfo) Path() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *FileInfo) Isdir() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FileInfo) MutateIsdir(n byte) bool {
	return rcv._tab.MutateByteSlot(8, n)
}

func FileInfoStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func FileInfoAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func FileInfoAddPath(builder *flatbuffers.Builder, path flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(path), 0)
}
func FileInfoAddIsdir(builder *flatbuffers.Builder, isdir byte) {
	builder.PrependByteSlot(2, isdir, 0)
}
func FileInfoEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
