// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package __std

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FileSystemResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsFileSystemResponse(buf []byte, offset flatbuffers.UOffsetT) *FileSystemResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FileSystemResponse{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *FileSystemResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FileSystemResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FileSystemResponse) RetvalType() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FileSystemResponse) MutateRetvalType(n byte) bool {
	return rcv._tab.MutateByteSlot(4, n)
}

func (rcv *FileSystemResponse) Retval(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func FileSystemResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func FileSystemResponseAddRetvalType(builder *flatbuffers.Builder, retvalType byte) {
	builder.PrependByteSlot(0, retvalType, 0)
}
func FileSystemResponseAddRetval(builder *flatbuffers.Builder, retval flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(retval), 0)
}
func FileSystemResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
