// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package __std

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FileInfoArgs struct {
	_tab flatbuffers.Table
}

func GetRootAsFileInfoArgs(buf []byte, offset flatbuffers.UOffsetT) *FileInfoArgs {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FileInfoArgs{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *FileInfoArgs) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FileInfoArgs) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FileInfoArgs) Path() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func FileInfoArgsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func FileInfoArgsAddPath(builder *flatbuffers.Builder, path flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(path), 0)
}
func FileInfoArgsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
