// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package __std

type Format = int8
const (
	FormatAuto Format = 0
	FormatJSON Format = 1
	FormatYAML Format = 2
	FormatRaw Format = 3
)

var EnumNamesFormat = map[Format]string{
	FormatAuto:"Auto",
	FormatJSON:"JSON",
	FormatYAML:"YAML",
	FormatRaw:"Raw",
}

