// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package __std

type FulfilmentValue = byte
const (
	FulfilmentValueNONE FulfilmentValue = 0
	FulfilmentValueData FulfilmentValue = 1
	FulfilmentValueEndOfStream FulfilmentValue = 2
	FulfilmentValueError FulfilmentValue = 3
)

var EnumNamesFulfilmentValue = map[FulfilmentValue]string{
	FulfilmentValueNONE:"NONE",
	FulfilmentValueData:"Data",
	FulfilmentValueEndOfStream:"EndOfStream",
	FulfilmentValueError:"Error",
}

