// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package __std

type OutputFormat = int8
const (
	OutputFormatAuto OutputFormat = 0
	OutputFormatJSON OutputFormat = 1
	OutputFormatYAML OutputFormat = 2
)

var EnumNamesOutputFormat = map[OutputFormat]string{
	OutputFormatAuto:"Auto",
	OutputFormatJSON:"JSON",
	OutputFormatYAML:"YAML",
}

