// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package __std

type ResolutionValue = byte
const (
	ResolutionValueNONE ResolutionValue = 0
	ResolutionValueData ResolutionValue = 1
	ResolutionValueEndOfStream ResolutionValue = 2
	ResolutionValueError ResolutionValue = 3
)

var EnumNamesResolutionValue = map[ResolutionValue]string{
	ResolutionValueNONE:"NONE",
	ResolutionValueData:"Data",
	ResolutionValueEndOfStream:"EndOfStream",
	ResolutionValueError:"Error",
}

