// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package __std

type Retval = byte
const (
	RetvalNONE Retval = 0
	RetvalDeferred Retval = 1
	RetvalError Retval = 2
)

var EnumNamesRetval = map[Retval]string{
	RetvalNONE:"NONE",
	RetvalDeferred:"Deferred",
	RetvalError:"Error",
}

